### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by robthebold**
Added testing results for Xperia X 10 II vs Bass

### CODE REVIEW

**Comment by eLtMosen** [comment]
Hey rob!
Great to have you in the testing squad :D
Which build of Starship/ ex Starfish did you use?
The one that shortly surfaced on openrepos?
We currently have trouble building new working ones and the uploaded version did not connect to any watch since it had trouble with asteroidossync submodules. It was taken down when we realized and it is currently worked on to solve the issue.
The last know to work build is by @GeoffTearle and linked here.
https://github.com/AsteroidOS/starship/issues/9#issuecomment-926962170

**Comment by robthebold** [comment]
> Hey rob! Great to have you in the testing squad :D Which build of Starship/ ex Starfish did you use? The one that shortly surfaced on openrepos? We currently have trouble building new working ones and the uploaded version did not connect to any watch since it had trouble with asteroidossync submodules. It was taken down when we realized and it is currently worked on to solve the issue. The last know to work build is by @GeoffTearle and linked here. [#9 (comment)](https://github.com/AsteroidOS/starship/issues/9#issuecomment-926962170)

I saw that it'd been removed before I had a chance to test . . . Geoff's build was the one I've been testing on my Xperia 10 II with my LG Urbane for the last few months, and in general the core stuff works well. Every so often, I need to restart the service and reconnect to the watch, but otherwise quite usable. 

When I saw a new build announced, I had to get it, but alas that didn't happen. :( 

_But_ still I figured I better finally report on the latest working version I'd tried -- I'd been putting off sharing that update for too long.

BTW, due to some _very_ odd happenstances involving an underwear drawer(!), I have a _second_ Bass that I can share with a developer who doesn't have an Asteroid capable smartwatch. Anyone in that situation, PM me . . .

**Comment by GeoffTearle** [comment]
> Hey rob! Great to have you in the testing squad :D Which build of Starship/ ex Starfish did you use? The one that shortly surfaced on openrepos? We currently have trouble building new working ones and the uploaded version did not connect to any watch since it had trouble with asteroidossync submodules. It was taken down when we realized and it is currently worked on to solve the issue. The last know to work build is by @GeoffTearle and linked here. [#9 (comment)](https://github.com/AsteroidOS/starship/issues/9#issuecomment-926962170)

Hey @eLtMosen do you know if the issue that's being experienced is related to direc85's issue here?: https://github.com/AsteroidOS/asteroidsyncservice/issues/36
Sorry I'm a bit out of touch with everything, and haven't been on the Matrix channel for quite a while.

@robthebold Sorry for derailing your PR conversation :sweat_smile:

**Comment by eLtMosen** [comment]
> > BTW, due to some _very_ odd happenstances involving an underwear drawer(!), I have a _second_ Bass that I can share with a developer who doesn't have an Asteroid capable smartwatch. Anyone in that situation, PM me . . .

OMG, thousand apologies.
I edited your comment without even realizing being able to do so and cut off your message.
I was meaning to do a quoted reply and miss clicked. wowoow /o\

**Comment by FlorentRevest** [comment]
For the time being, this change looks good :) We'll try to improve the state of starship but for now that reflects how it is ;)

Thanks for the feedback @robthebold !

**Pull request merged**
